WebGuiaPotiguar/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, signup, EmpresaCreate, EmpresaUpdateView, EmpresaDeleteView, EmpresaListView, EmpresaDetailView

urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('empresas/', EmpresaListView.as_view(), name='empresa_list'),
    path("empresas/<int:pk>", EmpresaUpdateView.as_view(), name="empresa_update"),
    path("empresas/<int:pk>/delete", EmpresaDeleteView.as_view(), name="empresa_delete"),
    path("empresas/<int:pk>/detail/", EmpresaDetailView.as_view(), name="empresa_detail"),
    path("empresas/registro_empresa/", EmpresaCreate.as_view(), name="empresa_form"),
]

mainapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Empresa(models.Model):
        
    CATEGORIA_CHOICES = (
        ('AL','ALIMENTAÇÃO E BEBIDAS'),
        ('AU', 'AUTOMOTIVA'),
        ('SA', 'SAUDE'),
        ('TI', 'TECNOLOGIA DA INFORMAÇÃO'),
        ('SP', 'SERVIÇOS PESSOAIS'),
        ('SE', 'SERVIÇOS ESPECIALIZADOS'),
        ('ED', 'EDUCAÇÃO'),
        ('CO', 'CONSTRUÇÃO'),
        ('VE', 'VESTUÁRIO'),
        ('ET', 'ENTRETENIMENTO')
    )

    razao_social = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=14)
    email = models.CharField(max_length=50)
    endereco = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    user  = models.ForeignKey(User, on_delete=models.CASCADE)
    descricao = models.TextField(max_length=256, blank=True)
    categoria = models.CharField(max_length=30, choices=CATEGORIA_CHOICES, blank=True)

    class Meta:
        verbose_name = 'Empresa'
        verbose_name_plural = 'Empresas'

    def __str__(self):      
        return self.razao_social

    def get_absolute_url(self):
        return reverse('empresa_update', kwargs={'pk': self.pk})


    

mainapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Empresa

class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Campo Obrigatório')
    last_name = forms.CharField(max_length=30, required=True, help_text='Campo Obrigatório')
    email = forms.EmailField(required=False, help_text='Obrigatório. Por favor insira um e-mail válido')

    class Meta:
        model = User
        fields = {'username', 'first_name', 'last_name', 'email', 'password1', 'password2'}



    

mainapp/views.py
from mainapp.forms import SignupForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .models import Empresa
from django.urls import reverse_lazy


class EmpresaCreate(CreateView):
    model = Empresa
    fields = ["razao_social","cnpj","email","endereco","cidade","estado",]
    success_url = reverse_lazy('empresa_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EmpresaUpdateView(UpdateView):
    model = Empresa
    fields = ["razao_social","cnpj","email","endereco","cidade","estado", 'descricao', 'categoria']
    success_url = reverse_lazy('empresa_list')


class EmpresaDeleteView(DeleteView):
    model = Empresa
    success_url = reverse_lazy('empresa_list')


class EmpresaListView(ListView):
    model = Empresa
    template_name = 'mainapp/empresa_list'

    def get_queryset(self):
        return Empresa.objects.filter(user=self.request.user)

class EmpresaDetailView(DetailView):
    model = Empresa

def index(request):
    categorias = Empresa.objects.all().distinct()
    return render(request, 'index.html', {'categorias': categorias})


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


mainapp/templates/base.html
{% load static %}

{% include 'head.html' %}

<html lang="en">

{% include 'header.html' %}

{% block body %}

  <body>

    {% block content %}


    {% endblock content %}


  </body>

{% endblock body %}

{% include 'footer.html' %}

{% include 'scripts.html' %}

</html>

mainapp/templates/footer.html
{% load static %}

{% block footer %}
  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>OnePage</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              {% csrf_token %}  
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="mr-md-auto text-center text-md-left">
        <div class="copyright">
          &copy; Copyright <strong><span>OnePage</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->
  {% endblock footer %}

mainapp/templates/head.html
{% load static %}
{% block head %}

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>OnePage Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{%  static 'img/favicon.png' %}" rel="icon">
  <link href="{%  static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{%  static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{%  static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{%  static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{%  static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{%  static 'vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{%  static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{%  static 'vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
    * Template Name: OnePage - v2.2.0
    * Template URL: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

{% endblock head %}

mainapp/templates/header.html
{% load static %}
{% block header %}

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><a href="{% url 'index' %}">WGP</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="index.html">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#team">Team</a></li>
          <li><a href="#pricing">Pricing</a></li>
          <li class="drop-down"><a href="">Drop Down</a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="drop-down"><a href="#">Deep Drop Down</a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a href="#contact">Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->

      <a href="{% url 'login' %}" class="get-started-btn scrollto">Faça Login</a>

    </div>
  </header><!-- End Header -->

{% endblock header %}

mainapp/templates/index.html
{% extends 'base.html' %}

{% block body %}


{% block content %}

<section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
        <div class="row justify-content-center">
            <div class="col-xl-7 col-lg-9 text-center">
                <h1>Web Guia Potiguar</h1>
                <h2>A sua vitrine digital. Trazendo o mundo para mais próximo do seu negócio</h2>
            </div>
        </div>
        <div class="text-center">
            <a href="#about" class="btn-get-started scrollto">Get Started</a>
        </div>

        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for empresa in categorias %}
                    {% if forloop.first %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}" class="active"></li>
                    {% else %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}"></li>

                    {% endif %}
                {% endfor %}

                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                {% for empresa in categorias %}
                {% if forloop.first %}
                <div class="carousel-item active  ">
                    {% else %}
                    <div class="carousel-item  ">
                        {% endif %}
                            <div class="col-md-6 col-lg-3 d-flex" data-aos="zoom-in"
                                data-aos-delay="200">
                                <div class="icon-box">
                                    <div class="icon"><i class="ri-stack-line"></i></div>
                                    <h4 class="title"><a href="">{{empresa.get_categoria_display}}</a></h4>
                                    <p class="description">{{empresa.razao_social}}</p>
                                </div>
                            </div>
                        </div>

                        {% endfor %}
                    </div>

                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

</section>

{% include 'sections/clients_section.html' %}

{% endblock content %}

{% endblock body %}

mainapp/templates/mainapp/empresa_detail.html
{% extends 'base.html' %}
{% block content %}

    <div class="col-lg-8 mt-5 mt-lg-0" style="padding-top: 100px">

    <h2 class="display-4">{{empresa.razao_social}}</h2>
    <div class="row">
        <div class="col-4">
            <div class="list-group" id="list-tab" role="tablist">
            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-categoria" role="tab" aria-controls="profile">Categoria</a>
            <a class="list-group-item list-group-item-action"  id="list-messages-list" data-toggle="list" href="#list-descricao" role="tab" aria-controls="messages">Descrição</a>
            <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-produtos" role="tab" aria-controls="home">Produtos</a>
            </div>
        </div>
        <div class="col-8">
            <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="list-categoria" role="tabpanel" aria-labelledby="list-home-list">{{empresa.get_categoria_display}}</div>
            <div class="tab-pane fade text-justify" id="list-descricao" role="tabpanel" aria-labelledby="list-profile-list">{{empresa.descricao}}</div>
            <div class="tab-pane fade" id="list-produtos" role="tabpanel" aria-labelledby="list-messages-list">...</div>
            </div>
        </div>
    </div>

    </div>

{% endblock content %}

mainapp/templates/mainapp/empresa_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Empresa Form</h1>
    <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="Save">Cadastrar Empresa</button>
</form>
{% endblock content %}

mainapp/templates/mainapp/empresa_list.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
      Hi {{ user.first_name }}!
      <a href="{% url 'empresa_form' %}">Cadastre sua empresa</a>
      <h1>Listagem de Empresas</h1>

      {% if empresa_list %}
        <table class="table">
          <thead>
            <tr>
              <th>Nome da Empresa</th>
              <th>CNPJ</th>
              <th>Página da Empresa</th> 
            </tr>
          </thead>
          
          <tbody>
            {% for empresa in empresa_list %}
            <tr>
              <td><a href="{{ empresa.get_absolute_url }}">{{ empresa.razao_social }}</a></td>
              <td>{{empresa.cnpj}}</td>
              <td><a href="{% url 'empresa_detail' pk=empresa.id%}">Página da Empresa</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>

        {% else %}
          <p>Suas empresas ainda não foram cadastradas.</p>
        {% endif %} 

    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Log In</a>
    {% endif %}
{% endblock %}

mainapp/templates/scripts.html
  {% load static %}
  {% block scripts %}
  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.j' %}s"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %%}"></script>

  {% endblock scripts %}

mainapp/templates/sections/about_section.html
{% block about_section %}
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>About Us</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. </p>
        </div>

        <div class="row content">
          <div class="col-lg-6">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore
              magna aliqua.
            </p>
            <ul>
              <li><i class="ri-check-double-line"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat</li>
              <li><i class="ri-check-double-line"></i> Duis aute irure dolor in reprehenderit in voluptate velit</li>
              <li><i class="ri-check-double-line"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat</li>
            </ul>
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0">
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
              voluptate
              velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <a href="#" class="btn-learn-more">Learn More</a>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->
    {% endblock about_section %}

mainapp/templates/sections/about_video_section.html
{% block about_video_section %}
    <!-- ======= About Video Section ======= -->
    <section id="about-video" class="about-video">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-6 video-box align-self-baseline" data-aos="fade-right" data-aos-delay="100">
            <img src="{% static 'img/about-video.jpg' %}" class="img-fluid" alt="">
            <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="venobox play-btn mb-4" data-vbtype="video"
              data-autoplay="true"></a>
          </div>

          <div class="col-lg-6 pt-3 pt-lg-0 content" data-aos="fade-left" data-aos-delay="100">
            <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
            <p class="font-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore
              magna aliqua.
            </p>
            <ul>
              <li><i class="bx bx-check-double"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
              <li><i class="bx bx-check-double"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
              <li><i class="bx bx-check-double"></i> Voluptate repellendus pariatur reprehenderit corporis sint.</li>
              <li><i class="bx bx-check-double"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla
                pariatur.</li>
            </ul>
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
              voluptate
              velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum
            </p>
          </div>

        </div>

      </div>
    </section><!-- End About Video Section -->

    {% endblock about_video_section %}

mainapp/templates/sections/clients_section.html
{% load static %}

{% block client_section %}
    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients section-bg">
      <div class="container">

        <div class="row">

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center" data-aos="zoom-in">
            <img src="{%  static 'img/clients/client-1.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center" data-aos="zoom-in">
            <img src="{%  static 'img/clients/client-2.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center" data-aos="zoom-in">
            <img src="{%  static 'img/clients/client-3.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center" data-aos="zoom-in">
            <img src="{%  static 'img/clients/client-4.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center" data-aos="zoom-in">
            <img src="{%  static 'img/clients/client-5.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center" data-aos="zoom-in">
            <img src="{%  static 'img/clients/client-6.png' %}" class="img-fluid" alt="">
          </div>

        </div>

      </div>
    </section><!-- End Clients Section -->
    {% endblock client_section %}

mainapp/templates/sections/contact_section.html
{% block contact_section %}
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint
            consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit
            in iste officiis commodi quidem hic quas.</p>
        </div>

        <div>
          <iframe style="border:0; width: 100%; height: 270px;"
            src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621"
            frameborder="0" allowfullscreen></iframe>
        </div>

        <div class="row mt-5">

          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="icofont-google-map"></i>
                <h4>Location:</h4>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>

              <div class="email">
                <i class="icofont-envelope"></i>
                <h4>Email:</h4>
                <p>info@example.com</p>
              </div>

              <div class="phone">
                <i class="icofont-phone"></i>
                <h4>Call:</h4>
                <p>+1 5589 55488 55s</p>
              </div>

            </div>

          </div>

          <div class="col-lg-8 mt-5 mt-lg-0">

            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="form-row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name"
                    data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                  <div class="validate"></div>
                </div>
                <div class="col-md-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email"
                    data-rule="email" data-msg="Please enter a valid email" />
                  <div class="validate"></div>
                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject"
                  data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validate"></div>
              </div>
              <div class="form-group">
                <textarea class="form-control" name="message" rows="5" data-rule="required"
                  data-msg="Please write something for us" placeholder="Message"></textarea>
                <div class="validate"></div>
              </div>
              <div class="mb-3">
                <div class="ing">ing</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->
    {% endblock contact_section %}

mainapp/templates/sections/counts_section.html
{% block count_section %}
    <!-- ======= Counts Section ======= -->
    <section id="counts" class="counts section-bg">
      <div class="container">

        <div class="row justify-content-end">

          <div class="col-lg-3 col-md-5 col-6 d-md-flex align-items-md-stretch">
            <div class="count-box">
              <span data-toggle="counter-up">65</span>
              <p>Happy Clients</p>
            </div>
          </div>

          <div class="col-lg-3 col-md-5 col-6 d-md-flex align-items-md-stretch">
            <div class="count-box">
              <span data-toggle="counter-up">85</span>
              <p>Projects</p>
            </div>
          </div>

          <div class="col-lg-3 col-md-5 col-6 d-md-flex align-items-md-stretch">
            <div class="count-box">
              <span data-toggle="counter-up">12</span>
              <p>Years of experience</p>
            </div>
          </div>

          <div class="col-lg-3 col-md-5 col-6 d-md-flex align-items-md-stretch">
            <div class="count-box">
              <span data-toggle="counter-up">15</span>
              <p>Awards</p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Counts Section -->
    {% endblock count_section %}

mainapp/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Cadastre-se</h2>
    <form method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Cadastrar</button>
    </form>
{% endblock content %}